### ISSUE TITLE
TypeError: current.reduce is not a function

### ISSUE THREAD

**Issue by kellydavid** [arupex/pr#8]
Getting this error when I run `prme`:

```
 TypeError: current.reduce is not a function
    at diffCommits (/usr/local/lib/node_modules/prme/core-plugins/githubCommitDiff.js:55:45)
    at Request._callback (/usr/local/lib/node_modules/prme/core-plugins/githubCommitDiff.js:120:35)
    at Request.self.callback (/usr/local/lib/node_modules/prme/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/prme/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/prme/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
```

What causes this error to occur?

**Comment by dirwin517** [comment]
usually a sign 
1. you are not in a git project directory
2. the current branch has not been pushed to remote or has been since deleted (usually this)
3. or github is down
4. your local head is really messed up

This occurs doing githubCommitDiff.js which basically asks your local machine what branch its on, and looks at the config to find the 'master' base branch, and does an api call to look at the commit diff via githubs api. if either branch does not exist or something is messed up between them it can cause issue

Hope that helps!

**Comment by kellydavid** [comment]
Thanks, I've checked each of your suggestions but I still got the error. I changed the origin remote url to not have the `.git` extension and prme got a little further.

I'm now seeing the error:
```
prLink  is being ignored till end
github data is not array { message: 'Not Found',
  documentation_url: 'https://developer.github.com/enterprise/2.14/v3/repos/commits/#list-commits-on-a-repository' }
 TypeError: Cannot create property 'sha' on string 'Not Found'
    at setter (/usr/local/lib/node_modules/prme/node_modules/map-attack/index.js:23:22)
    at /usr/local/lib/node_modules/prme/node_modules/map-attack/index.js:52:20
    at Array.map (<anonymous>)
    at arupex_map_attack (/usr/local/lib/node_modules/prme/node_modules/map-attack/index.js:51:40)
    at diffCommits (/usr/local/lib/node_modules/prme/core-plugins/githubCommitDiff.js:53:29)
    at Request._callback (/usr/local/lib/node_modules/prme/core-plugins/githubCommitDiff.js:120:35)
    at Request.self.callback (/usr/local/lib/node_modules/prme/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/prme/node_modules/request/request.js:1161:10)
```
I have a feature branch checked out locally and pushed to a remote called `origin`. The format of the `origin` url is `https://<github_hostname>/<my_org>/<my_repo>`. 

Could I be missing something else here?
